spring:
  application:
    name: spring-pcf-eureka-client
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka.credentials.url}
  instance:
    nonSecurePort: 80
    hostname: ${vcap.application.uris[0]}